### ISSUE TITLE
Structure Scanner setting survival=false in the structure file if the survival option is checked when scanning

### ISSUE THREAD

**Issue by TechStack** [shadowmage45/AncientWarfare#18]
When scanning in a new structure with the build in survival option checked the .AWS file gets created with  survival=false inside the file.
It must be opened with a text editor and manually set to true before it can be built in survival.

**Comment by shadowmage45** [comment]
Hmm..I must not be reading the variable out of the GUI properly -- I will look into this for a fix shortly, should be fairly simple.

Thanks for the report  (and thanks for your help tracking down issues in general :) )
