### ISSUE TITLE
Duplication bug!

### ISSUE THREAD

**Issue by sylphio** [shadowmage45/AncientWarfare#2]
Hi, 

Here is a way to duplicate item on multiplayer using your mod.
- Create a Transport Boat on water  and fill-it items.
- Take place in the boat and disconnect
- Relog on the server

When reconnecting all the item contained in the boat will be dropped on/under the boat but all the item inside the boat will still be here creating a second copy.

Thank you for your nice mod
Sylp

**Comment by Gorgok** [comment]
I was just going to post that one, though its not just boats.

Any mount with items in it, ammo, upgrades, cargo, etc... mounted while you log off will dupe all of its inventory on rejoining. Mounts go away with the player, which is probably what i causing it. Would probably make more sense with siege weapons if mounts dismounted the player when they log off, which would solve the dupe bug as a side effect.

**Comment by shadowmage45** [comment]
Thanks for the heads up.  Now that I'm aware of the issue, I should be able to find a solution for it fairly soon.

I'm not sure if I can control the mount saving with the player, but I should be able to find a way to make it not drop its inventory at least.
