### ISSUE TITLE
Death message broadcast to other players is incorrect in SMP when killed by NPC

### ISSUE THREAD

**Issue by TechStack** [shadowmage45/AncientWarfare#27]
Shadowmage, I do not have the exact message handy but when a player dies from an NPC on a server the message broadcast to other players is incorrect.

Example : 
Desired sate it should read : TechStack was shot by an Expert archer

current state it reads: Enitty.Ancientwarfare.NPC was killed by an arrow. 

( sorry i do not have the exact message at this time next time someone dies on my server i'll try to grab a screenshot )

its a little confusing for everyone because the person that died is never mentioned instead it looks like the NPC died.

**Comment by keenerb** [comment]
This is a very common error across MANY smp mods.

I've been told it has to do with the server-side not performing language lookups/translations properly.

The MoCreatures dev worked around it with some sort of client-side hack.

**Comment by shadowmage45** [comment]
@keenerb yes, and yes.  It is caused by incorrect localization lookups.  I had thought I had it solved a few releases ago, but might have fixed it on the wrong side (client/server), or it just wasn't the proper fix :)

I'll take a look at this shortly, should be fairly easy to fix.
