### ISSUE TITLE
Severe FPS lag with warehouses

### ISSUE THREAD

**Issue by keenerb** [shadowmage45/AncientWarfare#4]
I'm deploying my first warehouses, and I've noticed that the more items I have stored, the lower my FPS is when I open the warehouse interface.

There's a direct correlation between # of items displayed in warehouse and frames per second:

No items displayed, 55fps:  http://i.imgur.com/eIJlb2j.png

Some items displayed, 35fps:  http://i.imgur.com/MZ3wGjn.png
All items displayed, 14 fps:  http://i.imgur.com/iT9YQLD.png

**Comment by shadowmage45** [comment]
Very interesting.  There is likely some room for optimization in my rendering -- or at least I hope there is :)

I will take a look at this for one of the next few updates, have a few fairly critical bugs to track down and squash first, but thanks for letting me know.
