### ISSUE TITLE
translation on death by npc is incorrect

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/AncientWarfare#42]
need translation entry for entity.AncientWarfare.entity.npc.name for death-message purposes

**Comment by shadowmage45** [comment]
appears to already be fixed in dev-code. will re-open if not

**Comment by TechStack** [comment]
Seems to still be a problem intermittently, this was from the server today using the latest .042 version
![image](https://f.cloud.github.com/assets/4016300/2009002/f83237a8-8756-11e3-9850-724ce13502ec.png)

perhaps it has something to do with the type of death i noticed the one with the Entity.AncientWarfare.... was slain but the others were killed by missile damage.

**Comment by shadowmage45** [comment]
hmm..pretty sure I had added the necessary language file entries for this, but will re-open and do further investigation

**Comment by shadowmage45** [comment]
Have not been able to duplicate this issue, and the translation key indicated _is_ in the language file (which is probably why I can't duplicate it).

Please open a new issue if this is still present in the 1.7 releases when we get there.
