### ISSUE TITLE
Selecting cow farm boundaries while holding a stack of cow farms ties ALL of the civs to the same boundary

### ISSUE THREAD

**Issue by keenerb** [shadowmage45/AncientWarfare#5]
http://i.imgur.com/8piqxdu.png

Click to set boundaries while holding a stack of cow farms.

Place a cow farm.  The other cow farms in the stack are now tied to the same civic boundaries, you can see overlapping pink/white marker lines in my screenshot.  Placeing the civic doesn't do anything; when you break it, it's still tied to a purple civic boundary and you can't reset it.

**Comment by shadowmage45** [comment]
Thanks for the report.  

Civic items should not be stackable (I probably missed a max-stack size somewhere) -- all items in a 'stack' share NBT data, hence all civic items in a stack would have the same bounds set  (you should be able to shift-right click to clear the bounds from the remaining items in the stack after placing the first one).

I will look into a resolution to this shortly, hopefully for this weekends update.

**Comment by keenerb** [comment]
Yeah, looks like all the civics are stackable.
