### ISSUE TITLE
Mailbox Listing Scroll Box not scrolling the list

### ISSUE THREAD

**Issue by TechStack** [shadowmage45/AncientWarfare#54]
You can see in the attached screenshot that once the mailbox listing gets very long and flows past the bottom of the page the scroll bar will let you scroll up and down but the list will not move with it. It stays anchored to the top of the screen.

![2014-02-11_21 18 02](https://f.cloud.github.com/assets/4016300/2155047/b8f2d4c2-943e-11e3-9968-dc671c9cad63.png)

**Comment by shadowmage45** [comment]
will be fixed and available in the next update
