### ISSUE TITLE
Bucket Dupe in Alchemy Station

### ISSUE THREAD

**Issue by TechStack** [shadowmage45/AncientWarfare#57]
Step to reproduce:
1. put research book into alchemy station & select Cement as the item to craft.
2. put a full water bucket, sand & clay into the inventory.
3. Click start.
4. When the full water bucket  is consumed 1 empty bucket will be in station inventory a second empty bucket will be dropped onto the ground.

I haven't tested other recipes only the one for cement.

Thanks :)

**Comment by shadowmage45** [comment]
Hmm..that is no good.  I will investigate this shortly and should have a fix for next release.
