### ISSUE TITLE
Water/milk buckets

### ISSUE THREAD

**Issue by Lazsa** [shadowmage45/AncientWarfare#58]
Lazsa  commented just now 

when using buckets With milk or water in the autocrafing stations the empty buckets will not be returned. They simply disapear.

ALso the alchemist station bugs realy bad when making cement. Then it is duplicating buckets big time.

i got an utube video for it that i am gonna post soon.

LAzsa

**Comment by shadowmage45** [comment]
I've fixed the alchemist station/cement/duplication bug -- should be available with the next udpate.

Thanks for informing me about the auto-crafting station issues, I will look into it and should be able to have it fixed in the next update as well.

**Comment by shadowmage45** [comment]
have fixed in dev-code.  the fix should be available with the next public release.
