### ISSUE TITLE
Not generating structures in Middle Earth dimension

### ISSUE THREAD

**Issue by keenerb** [shadowmage45/AncientWarfare#6]
AW .34, MCPC+ build 150

I already mentioned this on the forum, but I like issue trackers, so I'll post here and include a workaround.

You mentioned that it may be due to AW loading before all the biomes are loaded, so I renamed the zip from from aw-<otherstuff> to zaw-<otherstuff> and now it seems to generate JUST FINE.

**Comment by shadowmage45** [comment]
Thanks for reporting things here -- makes it quite a bit easier to keep track of issues (much better than a manual if-I-remember type list :) )

If things are loading fine with a rename of the zip, I will see what I can do about delaying the loading/parsing of biome information until post-load (possibly on world-load, after all mods have definitely been loaded).  Definitely a solvable issue, should be able to have a resolution shortly.

**Comment by keenerb** [comment]
I have towers and fountains and obsidian vaults all over the place now, I'm pretty pleased.

I also fell victim to your damned lava farm.  :/

**Comment by shadowmage45** [comment]
LoL -- isn't it just evil?   jodi and I had quite a bit of fun coming up with a few interesting buildings :)

Anyhow, I've just patched in the code to delay loading of biomes until post-init -- will catch any/all biomes that other mods register prior to that stage -- however, it is the last loading stage, and cannot (easily/cleanly) be delayed any further, so this fix also relies on other mod authors registering things when they should be (during pre/init stages).

Closed by https://github.com/shadowmage45/AncientWarfare/commit/b080ff2702f00980307e8e0b3ba0077d0e96f6fc
