### ISSUE TITLE
Balistas + Siege weapons

### ISSUE THREAD

**Issue by Lazsa** [shadowmage45/AncientWarfare#61]
Hey Shadowmage.

I want to see the siege weapons to shoot downwards better.
I got 2 ballistas on top of my gatehouse. its like 8 Blocks up in the air from the ground.
even with 4 Upgrades forcing them to aim downwards they cant hit any mobs.

Even on my walls below like 4 Blocks above ground they cant seem to hit the incoming mobs. they just shoot over their heads. 

ALso i want to see if its possible to atleast on the fixed siege weapons that Couriers could
fill them up With ammo. Not sure if they do more dmg if filled with ammo tough.

At the moment NPC's can fire siege weapons without ammo in them. Not sure if that was what u wanted but ....

I hope u can fix so that atleast some of the Siege weapons can shoot downwards better.
Fixed ballista stand turrets should deffenetly be ideal for this. 

Havent tested the mobile siege weapons enough to tell if they are better to aim downwards, but i hope u can take a look into this. Atleast do something about it 
for the 1.7 Version

Ty Lazsa

**Comment by Lazsa** [comment]
![2014-04-16_16 02 11](https://cloud.githubusercontent.com/assets/6875488/2720503/10383a26-c570-11e3-9850-a1ced1e3004c.png)

Picture above they are not shooting. I tried With ammo and without ammo just incase.

**Comment by shadowmage45** [comment]
Hmm..they should shoot down at least a little bit -- I think they can go to -5 or -15 degrees.   The setup you have in your image shouldn't be too much of a problem for them, although they -are- supposed to have problems on taller walls (you are supposed to use catapults / indirect fire weapons from the top of taller fortifications).

I'll verify that they are working as intended (max slight down-angle), but for the most part, no, they cannot shoot downwards.  If they are working as intended currently, I will be leaving them as is, and revisit this issue when I am rewriting them for 1.7.
