### ISSUE TITLE
NPCs refill with default armor when repacked/replaced

### ISSUE THREAD

**Issue by keenerb** [shadowmage45/AncientWarfare#9]
Created a survival world, cheated in a notebook, npc recruiting station, and components to make a novice footsoldier.

Place the footsoldier, unequipped leather pants.  Repacked and re-placed footsoldier, footsoldier was again fully equipped, unequipped pants, rinse and repeat as desired.

**Comment by TechStack** [comment]
We have also seen this dupe glitch on our server.
